# Generated by Django 5.0.6 on 2024-06-11 20:28

import marcala_place.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcala_place', '0002_alter_vendor_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=marcala_place.models.usuario_directory_path),
        ),
    ]
